---
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: cosmo
---

<!--html_preserve-->
<div class="container">
<!-- Static navbar -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
        
          <li class="">
					<a href="/get_to_know_tek.html">Get To Know Tek</a>
	</li>              
				  
				  
	<li class="">
					<a href="/past_project.html">Past Project</a>
	</li>

	<li class="">
					<a href="/cheat_sheet.html">Cheat Sheet</a>
	</li>

      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav><!--navbar navbar-default-->
</div>
<!--/html_preserve-->



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Organazing Data Frame <!--{-}-->

##Base R functions and operators <!--{.tabset}-->



###dataframe

###subset
columnwise subset
Use `$` operator
Use matrix notation *df*[,*column number*] or *df*[, *"column name"*]

* e.g.
```{r, comment=""}
head(mtcars)
```

```{r, eval=F, comment=""}
head(mtcars$mpg)
head(mtcars[,1])
head(mtcars[,"mpg"])
```

```{r, echo=F, comment=""}
head(mtcars$mpg)
```


rowwise
Use matrix notation *df*[*row number*,] or *df*[*"row name"*, ]
```{r, eval=F, comment=""}
mtcars[1,]
mtcars["Mazda RX4",]
```

```{r, echo=F, comment=""}
mtcars[1,]
```




##dplyr

##tidyr