---
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    theme: cosmo
---
<style>
body {
    position: absolute;
    left: 0px;}
</style>

<!--html_preserve-->
<div class="container">
<!-- Static navbar -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="../index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
        
          <li class="">
					<a href="/get_to_know_tek.html">Get To Know Tek</a>
	</li>              
				  
				  
	<li class="">
					<a href="/past_project.html">Past Project</a>
	</li>

	<li class="">
					<a href="/cheat_sheet.html">Cheat Sheet</a>
	</li>

      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav><!--navbar navbar-default-->
</div>
<!--/html_preserve-->



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pkg=c("tm")
sapply(pkg, require, character=T)
```


<h1>Text Mining</h1><ol type="I">

<h2><li>Handling and Processing Strings</li></h2><ol type="1">

<h3><li>Reading in Text Data</li></h3>
read text data in table format

read.table(): main function to read file in table format
read.csv(): reads csv files separated by a comma","
read.csv2(): reads csv files separated by a semicolon";"
read.delim(): reads files separated by tabs"\t"
read.delim2(): similar to read.delim()
read.fwf(): read fixed width format files

stringAsFactors=F

Raw text data
readLines()


<h3><li>String Manipulation</li></h3>


grep
gsub
gregexpr
paste
paste0
substr
str_split

basic functions
nchar():number of characters
tolower():convert to lower case
toupper():convert to upper case
casefold():case folding
chartr():character translation
abbreviate():abbreviation
substring():substrings of a character vector
substr():substrings of a character vec



print():generic printing.  argument quote=F
noquote():print with no quotes
cat():concatenation
format():special formats
toString():convert to string
sprintf():printing


pkg
stringr
nchar on factor fails. use str_length
str_trim

regex
Metacharacters
<!--
. the period or dot\\.
$the dollar sign\\$
*the asterisk or star\\*
+the plus sign\\+
?the question mark\\?
|the vertical bar or pipe symbol\\|
\the backslash\\\\
^the caret\\^
[the opening square bracket\\[
]the closing square bracket\\]
{the opening curly bracket\\{
}the closing curly bracket\\}
(the opening round bracket\\(
)the closing round bracket\\)
-->

encoding





R has five main types of objects to store data: vector, factor, matrix (and array), data.frame, and list.
character string
